apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-service-deployment
  labels:
    app: model-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: model-service
  template:
    metadata:
      labels:
        app: model-service
    spec:
      containers:
        - name: backend
          image: xterrafuny/mlops-hse-25f:1.0.0
          ports:
            - containerPort: 8000
              name: api
