apiVersion: v1
kind: Service
metadata:
  name: model-service-svc
spec:
  type: NodePort
  selector:
    app: model-service
  ports:
    - protocol: TCP
      port: 8000
      nodePort: 30001
      targetPort: 8000
