[project]
name = "cityscapes-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.2.6",
    "pandas>=2.3.3",
    "requests>=2.34.2",
]

[project.scripts]
cityscapes-tools = "cityscapes_tools:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "fire>=0.7.1",
]
