# @package _global_.paths

repo_root: .
cityscapes_project_dir: ${paths.repo_root}/cityscapes-segmentation
cityscapes_checkpoint: ${paths.cityscapes_project_dir}/cityscapes-segmentation/lightning/checkpoints/best.ckpt
cityscapes_input_dir: ${paths.cityscapes_project_dir}/data/gtFine/val
artifacts_dir: ${paths.repo_root}/inference-seminar/results
