# @package _global_.benchmark

onnx_path: ${export.onnx_path}
providers:
  - pytorch
  - cuda
  - tensorrt
num_images: 5
warmup_runs: 3
timed_runs: 20
seed: 42
results_csv: ${paths.artifacts_dir}/backend_benchmarks.csv
trt_engine_cache_path: ${paths.artifacts_dir}/trt_cache
save_predictions: false
